#!/usr/bin/env bash
#
# Check syntax and validity of DNS Zone files
#

# The named configuration directory. Zone databases live here.
conf_dir="/var/named/"

for fwd_zone in "$conf_dir"*db; do
    if [[ "$fwd_zone" =~ db$ ]]; then
        # Get the base zone info.
        zone_info=$(awk '/^@ IN NS/ {print $NF}' "$fwd_zone")
        rev_zone="${fwd_zone/%db/rev}"

        # Trim the zone name.
        zone_name="${zone_info%*.}"
        zone_name="${zone_info#*.}"

        # Derive the zone nameserver hostname and IP.
        zone_ns_hostname="${zone_info%%.*}"
        zone_ns_ip=$(awk "/^${zone_ns_hostname}/"'{print $NF}' "$fwd_zone")

        # Run named-checkzone against the current zone.
        echo -e "Checking $fwd_zone"
        named-checkzone "$zone_name" "$fwd_zone"

        # Run named-checkzone against reverse zones if found.
        if [[ -f "$rev_zone" ]]; then
            echo -e "Found reverse zone. Checking $rev_zone"
            named-checkzone "$zone_ns_ip" "$rev_zone"
        else
            "No reverse zone found for $zone_name"
        fi
    else
        echo "Skipping $fwd_zone"
    fi
done
